# Installation and import

In [1]:
#! pip install numpy

In [2]:
import numpy as np

# Review

## Creation

In [3]:
lst1 = [1,2,3,4,5,6]
arr1 = np.array(lst1)
arr2 = np.array((2,2,5,6,7,8),dtype='float')

In [4]:
print(arr1)
print(type(arr2))
print(arr2.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
float64


## Dont use np.array(list(range(str,stp,step))

In [5]:
%%time
np.array((range(1,100000000,3)))

Wall time: 2.14 s


array([       1,        4,        7, ..., 99999991, 99999994, 99999997])

In [6]:
%%time
np.arange(start=0,stop=100000000,step =3)

Wall time: 33 ms


array([       0,        3,        6, ..., 99999993, 99999996, 99999999])

## Reshaping

In [7]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2 = np.array([lst1,lst1])

# More Creation

In [9]:
np.linspace(1,10,14)

array([ 1.        ,  1.69230769,  2.38461538,  3.07692308,  3.76923077,
        4.46153846,  5.15384615,  5.84615385,  6.53846154,  7.23076923,
        7.92307692,  8.61538462,  9.30769231, 10.        ])

In [10]:
np.linspace(1,1,10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.linspace(start=1,stop=1,num = 10 , dtype='int8')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [12]:
np.ones((2,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random

In [14]:
#set dimantion
#values between 0-1
np.random.rand(2,2,2)

array([[[0.32772613, 0.57686449],
        [0.51185033, 0.91109355]],

       [[0.81046864, 0.50600019],
        [0.33311405, 0.45464354]]])

In [15]:
np.random.randint(0,10,size=(2,3,3) , dtype='int8')

array([[[9, 6, 6],
        [4, 6, 3],
        [9, 4, 9]],

       [[5, 0, 3],
        [7, 7, 1],
        [9, 3, 0]]], dtype=int8)

# Attributes

In [16]:
arr = np.random.randint(0,10,size=(4,4,4) , dtype='int8')
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.itemsize)
print(arr.strides)
print(arr.data)

int8
3
(4, 4, 4)
1
(16, 4, 1)


# Slicing / indexing

In [17]:
#printing
arr

array([[[4, 7, 1, 0],
        [9, 7, 4, 7],
        [2, 5, 8, 0],
        [0, 7, 5, 8]],

       [[4, 4, 9, 5],
        [6, 3, 4, 9],
        [7, 9, 9, 5],
        [5, 2, 9, 8]],

       [[4, 8, 8, 3],
        [4, 9, 0, 9],
        [4, 0, 0, 0],
        [0, 6, 1, 6]],

       [[4, 1, 9, 8],
        [8, 5, 2, 1],
        [4, 3, 5, 9],
        [5, 1, 9, 0]]], dtype=int8)

In [18]:
arr[1:2]

array([[[4, 4, 9, 5],
        [6, 3, 4, 9],
        [7, 9, 9, 5],
        [5, 2, 9, 8]]], dtype=int8)

In [19]:
arr[0:2,0:2,0:2]

array([[[4, 7],
        [9, 7]],

       [[4, 4],
        [6, 3]]], dtype=int8)

In [20]:
arr[0:-1,0:-1,0:-1]
#arr[:-1,:-1,:-1]

array([[[4, 7, 1],
        [9, 7, 4],
        [2, 5, 8]],

       [[4, 4, 9],
        [6, 3, 4],
        [7, 9, 9]],

       [[4, 8, 8],
        [4, 9, 0],
        [4, 0, 0]]], dtype=int8)

## Replace

In [21]:
arr[0:,0:1,0:1] = -1

In [22]:
arr

array([[[-1,  7,  1,  0],
        [ 9,  7,  4,  7],
        [ 2,  5,  8,  0],
        [ 0,  7,  5,  8]],

       [[-1,  4,  9,  5],
        [ 6,  3,  4,  9],
        [ 7,  9,  9,  5],
        [ 5,  2,  9,  8]],

       [[-1,  8,  8,  3],
        [ 4,  9,  0,  9],
        [ 4,  0,  0,  0],
        [ 0,  6,  1,  6]],

       [[-1,  1,  9,  8],
        [ 8,  5,  2,  1],
        [ 4,  3,  5,  9],
        [ 5,  1,  9,  0]]], dtype=int8)

# Copy

In [23]:
BAD_COPY = arr[0:2,0:2,0:2]
Good_COPY = arr[0:2,0:2,0:2].copy()

In [24]:
Good_COPY

array([[[-1,  7],
        [ 9,  7]],

       [[-1,  4],
        [ 6,  3]]], dtype=int8)

In [25]:
BAD_COPY

array([[[-1,  7],
        [ 9,  7]],

       [[-1,  4],
        [ 6,  3]]], dtype=int8)

In [26]:
arr[0:2,0:2,0:2] = 0

In [27]:
BAD_COPY

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int8)

In [28]:
Good_COPY

array([[[-1,  7],
        [ 9,  7]],

       [[-1,  4],
        [ 6,  3]]], dtype=int8)

## Boolean array

In [29]:
Good_COPY > BAD_COPY

array([[[False,  True],
        [ True,  True]],

       [[False,  True],
        [ True,  True]]])

# operators

In [30]:
Good_COPY+BAD_COPY

array([[[-1,  7],
        [ 9,  7]],

       [[-1,  4],
        [ 6,  3]]], dtype=int8)

In [31]:
Good_COPY*2

array([[[-2, 14],
        [18, 14]],

       [[-2,  8],
        [12,  6]]], dtype=int8)

In [32]:
Good_COPY/2

array([[[-0.5,  3.5],
        [ 4.5,  3.5]],

       [[-0.5,  2. ],
        [ 3. ,  1.5]]])

In [33]:
# inf == infinity
Good_COPY/BAD_COPY

C:\Users\itaig\AppData\Local\Temp\ipykernel_5716\325349128.py:2: RuntimeWarning: divide by zero encountered in divide
  Good_COPY/BAD_COPY


array([[[-inf,  inf],
        [ inf,  inf]],

       [[-inf,  inf],
        [ inf,  inf]]])

# Max Min Mean

In [34]:
arr.max()

9

In [35]:
arr.mean()

3.96875

In [36]:
arr.min()

-1

# Utils

In [37]:
np.sin(arr)

array([[[ 0.    ,  0.    ,  0.8413,  0.    ],
        [ 0.    ,  0.    , -0.757 ,  0.657 ],
        [ 0.909 , -0.959 ,  0.9893,  0.    ],
        [ 0.    ,  0.657 , -0.959 ,  0.9893]],

       [[ 0.    ,  0.    ,  0.412 , -0.959 ],
        [ 0.    ,  0.    , -0.757 ,  0.412 ],
        [ 0.657 ,  0.412 ,  0.412 , -0.959 ],
        [-0.959 ,  0.909 ,  0.412 ,  0.9893]],

       [[-0.8413,  0.9893,  0.9893,  0.1411],
        [-0.757 ,  0.412 ,  0.    ,  0.412 ],
        [-0.757 ,  0.    ,  0.    ,  0.    ],
        [ 0.    , -0.2793,  0.8413, -0.2793]],

       [[-0.8413,  0.8413,  0.412 ,  0.9893],
        [ 0.9893, -0.959 ,  0.909 ,  0.8413],
        [-0.757 ,  0.1411, -0.959 ,  0.412 ],
        [-0.959 ,  0.8413,  0.412 ,  0.    ]]], dtype=float16)

In [38]:
np.cos(arr)

array([[[ 1.    ,  1.    ,  0.5405,  1.    ],
        [ 1.    ,  1.    , -0.654 ,  0.754 ],
        [-0.4163,  0.2837, -0.1455,  1.    ],
        [ 1.    ,  0.754 ,  0.2837, -0.1455]],

       [[ 1.    ,  1.    , -0.911 ,  0.2837],
        [ 1.    ,  1.    , -0.654 , -0.911 ],
        [ 0.754 , -0.911 , -0.911 ,  0.2837],
        [ 0.2837, -0.4163, -0.911 , -0.1455]],

       [[ 0.5405, -0.1455, -0.1455, -0.99  ],
        [-0.654 , -0.911 ,  1.    , -0.911 ],
        [-0.654 ,  1.    ,  1.    ,  1.    ],
        [ 1.    ,  0.96  ,  0.5405,  0.96  ]],

       [[ 0.5405,  0.5405, -0.911 , -0.1455],
        [-0.1455,  0.2837, -0.4163,  0.5405],
        [-0.654 , -0.99  ,  0.2837, -0.911 ],
        [ 0.2837,  0.5405, -0.911 ,  1.    ]]], dtype=float16)